<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="./css/style.css">
</head>
<body>
    <a href="index.php">Accueil</a>
    <p><?php echo $etudiant['nom'] . " " . $etudiant['prenom'] ?></p>
    <table>
            <tr>
                <th>Matières</th>
                <?php foreach($matieres as $values):?>
                    <td><?= $values['libelle']?></td>
                <?php endforeach?> 
            </tr>
    </table>
</body>
</html>