<!DOCTYPE html>
<html lang="fr">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Pronote</title>
        <link rel="stylesheet" href="./css/index.css">
    </head>
    <body>
        <h1>Pronote</h1>

        <?php if(count($etudiants) > 0): ?>
            <ul>
                <?php foreach($etudiants as $key => $values):?>
                    <li><a href="etudiant.php?key=<?= intval($values['id']) ?>"><?= htmlspecialchars($values['nom']) . " " . htmlspecialchars($values['prenom']) ?></a></li>
                <?php endforeach; ?>
            </ul>
        <?php endif ?>

        <?php if (count($etudiants) > 0 AND count($matieres) > 0): ?>

        <form action="./" method="post">
            <label>Etudiant</label>
            <select name="idEtudiant">
                <?php foreach($etudiants as $key => $values):?>
                    <option value="<?= intval($values['id']) ?>"><?= htmlspecialchars($values['nom']) . " " . htmlspecialchars($values['prenom']) ?></option>
                <?php endforeach; ?>
            </select>
            <label>Matière</label>
            <select name="idMatiere">
                <?php foreach($matieres as $key => $values):?>
                    <option value="<?= intval($values['id']) ?>"><?= htmlspecialchars($values['libelle']) ?></option>
                <?php endforeach; ?>
            </select>
            <label>Note</label>
            <input type="number" name="note" min="0" max="20">
            <button type="submit">Ajouter</button>
        </form>
        <?php endif ?>
    </body>
</html>