<!DOCTYPE>
<header>
    <title>Administration</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../css/style.css">
    <link rel="stylesheet" href="../css/style3.css">
</header>
<body>
    <nav>
        <a href="../index.php">Accueil</a>
        <span> | </span>
        <a href="./index.php">Administration</a>
    </nav>
    <h1>Administration</h1>
    <a href="add-movie.php">Ajouter un film</a>
    
    <table>
        <thead>
            <tr>
                <th>Films</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($movies as $key => $movie): ?>
            <tr>
                <td><?= $movie['title']?></td>
                <td>
                    <a href="edit-movie.php?key=<?= $key ?>">Editer</a><span> | </span>
                    <a href="delete-movie.php?key=<?= $key ?>">Supprimer</a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</body>