<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscription</title>
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="./css/style.css">
    <link rel="stylesheet" href="./css/inscription.css">
</head>
<body>
    <h1>Inscription</h1>
    <form action="inscription.php" method="post">
        <input type="email" name="mail">
        <input type="password" name="motDePasse">
        <input type="submit" value="Inscription">
    </form>
</body>
</html>
