<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="index.php" method="post" enctype="multipart/form-data">
        <input type="file" name="fichier" accept="image/png, image/jpeg">
        <input type="hidden" name="MAX_FILE_SIZE" value="3000000">
        <input type="submit" value="Envoyer">
    </form>
</body>
</html>