<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Movies</title>
	</head>
	<body>
		<?php include 'navigation.phtml'; ?>
		<h1>Movies</h1>
		<form action="./" action="get">
			<input type="text" name="title" placeholder="Titre">
			<input type="number" name="maximumDuration" placeholder="Durée maximale (en minutes)">
			<button type="submit">Filtrer</button>
		</form>
		<?php foreach($movies as $key => $movie): ?>
			<a href="./movie.php?key=<?= htmlspecialchars($key) ?>">
				<article>
					<img src="<?= htmlspecialchars($movie['cover']) ?>" alt="<?= htmlspecialchars($movie['title']) ?>">
					<h2><?= htmlspecialchars($movie['title']) ?></h2>
					<span><?= formatDuration($movie['duration']) ?></span>
				</article>
			</a>
		<?php endforeach ?>
	</body>
</html>