<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<title>Movies</title>
		<link rel="stylesheet" href="./css/style.css">
		<link rel="stylesheet" href="./css/style2.css">
	</head>
	<body>
	<nav>
		<a href="./index.php">Accueil</a>
		<span> | </span>
		<a href="./administration/index.php">Administration</a>
	</nav>
		<h1>Movies</h1>
		<form action="./" action="get">
			<input type="text" name="title" placeholder="Titre">
			<input type="number" name="maximumDuration" placeholder="Durée maximale (en minutes)">
			<button type="submit">Filtrer</button>
		</form>
		<div class="films">
		<?php foreach($movies as $key => $movie): ?>
			<a href="./movie.php?key=<?= htmlspecialchars($key) ?>">
				<article>
					<img src="<?= htmlspecialchars($movie['cover']) ?>" alt="<?= htmlspecialchars($movie['title']) ?>">
					<h2><?= htmlspecialchars($movie['title']) ?></h2>
					<span><?= formatDuration($movie['duration']) ?></span>
				</article>
			</a>
		<?php endforeach ?>
		</div>
	</body>
</html>