<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<title><?= htmlspecialchars($movie['title']) ?></title>
	</head>
	<body>
		<nav>
			<a href="./index.php">Accueil</a>
			<a href="./administration/index.php">Administration</a>
		</nav>
		<h1><?= htmlspecialchars($movie['title']) ?></h1>
		<img src="<?= htmlspecialchars($movie['cover']) ?>" alt="<?= htmlspecialchars($movie['title']) ?>">
		<span>Durée : <?= formatDuration($movie['duration']) ?></span>
		<p><?= htmlspecialchars($movie['synopsis']) ?></p>
	</body>
</html>