<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accueil</title>
    <link rel="stylesheet" href="./css/style.css">
</head>
<body>
    <?php include('./php-include/nav.phtml'); ?>
    <h1>Accueil</h1>
    <?php foreach($images as $image): ?>
        <img src="./img/<?= $image['filename'] ?>">
    <?php endforeach ?>
</body>
</html>