<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profil</title>
    <link rel="stylesheet" href="./css/style.css">
</head>
<body>
    <?php include('./php-include/nav.phtml'); ?>
    <h1>Mon profil</h1>

    <form action="profil.php" method="post" enctype="multipart/form-data">
        <input type="file" name="fichier" accept="image/png, image/jpeg">
        <input type="hidden" name="MAX_FILE_SIZE" value="3000000">
        <input type="submit" value="Envoyer">
    </form>
    <section>
        <?php foreach($images as $image): ?>
            <div>
                <img src="./img/<?= $image['filename'] ?>">
                <form action="profil.php" method="post">
                    <input type="hidden" name="idImage" value="<?= $image['id'] ?>">
                    <button type="submit">Supprimer</button>
        
                </form>
            </div>
        <?php endforeach ?>
    </section>
</body>
</html>